<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KAGUMPA-G2BH5" name="com.cisco.testscripts.PremiumRouting.Sprint27_US29912_01_MaintainGeoRoutes_Mergedwithgeodata_Add" tests="1" failures="0" timestamp="28 Apr 2016 21:04:21 GMT" time="5.784" errors="1">
  <testcase name="maintainGeoRoutes_Mergedwithgeodata_Add" time="5.784" classname="com.cisco.testscripts.PremiumRouting.Sprint27_US29912_01_MaintainGeoRoutes_Mergedwithgeodata_Add">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at lib.cisco.util.ApplicationUtility.portal_Login(ApplicationUtility.java:539)
	at com.cisco.testscripts.PremiumRouting.Sprint27_US29912_01_MaintainGeoRoutes_Mergedwithgeodata_Add.maintainGeoRoutes_Mergedwithgeodata_Add(Sprint27_US29912_01_MaintainGeoRoutes_Mergedwithgeodata_Add.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at lib.cisco.util.SequentialExecution.runTestNGSequential(SequentialExecution.java:51)
	at lib.cisco.util.Runner.primaryExecution(Runner.java:250)
	at lib.cisco.util.Runner.releaseTesting(Runner.java:218)
	at lib.cisco.util.Runner.main(Runner.java:172)
]]>
    </error>
  </testcase> <!-- maintainGeoRoutes_Mergedwithgeodata_Add -->
</testsuite> <!-- com.cisco.testscripts.PremiumRouting.Sprint27_US29912_01_MaintainGeoRoutes_Mergedwithgeodata_Add -->
